modLoader="javafml"
loaderVersion="[40,)"
license="GNU General Public License v3.0"

[[mods]]
    modId="stabxmodernguns"
    version="6.3"
    displayName="Stabx Modern Guns"
    authors="Stabilizer King"
    credits="Stabilizer Gaming Studio amd the Stabx Community "
    description="Addon for MrcrayFish Gun mod Adding High Quality Guns with better sounds"

[[dependencies.stabxmodernguns]]
    modId="forge"
    mandatory=true
    versionRange="[40.1.84,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.stabxmodernguns]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.stabxmodernguns]]
    modId="cgm"
    mandatory=true
    versionRange="[1.3.3,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.stabxmodernguns]]
    modId="framework"
    mandatory=true
    versionRange="[0.4.2,)"
    ordering="NONE"
    side="BOTH"
[modproperties.stabxmodernguns]
    catalogueItemIcon="stabxmodernguns:m4"
